// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMjSRprdy2hnuc_Ce8cspRBPHgL7dsjek',
    appId: '1:569063379537:web:96d74dc4f8fdf0305a1e70',
    messagingSenderId: '569063379537',
    projectId: 'assistentflutter',
    authDomain: 'assistentflutter.firebaseapp.com',
    storageBucket: 'assistentflutter.firebasestorage.app',
    measurementId: 'G-5XSLZS6LNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu-SW0dk9FOkuN5kTuGZDuOSz9SOtoByY',
    appId: '1:569063379537:android:cdfa867d7414ca9a5a1e70',
    messagingSenderId: '569063379537',
    projectId: 'assistentflutter',
    storageBucket: 'assistentflutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnjFEsYcgx3DAm0CYNWM9KVYJwvjVjgZo',
    appId: '1:569063379537:ios:dcdf6e7b07a33f6d5a1e70',
    messagingSenderId: '569063379537',
    projectId: 'assistentflutter',
    storageBucket: 'assistentflutter.firebasestorage.app',
    iosBundleId: 'com.example.siriGoogleAssistent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnjFEsYcgx3DAm0CYNWM9KVYJwvjVjgZo',
    appId: '1:569063379537:ios:dcdf6e7b07a33f6d5a1e70',
    messagingSenderId: '569063379537',
    projectId: 'assistentflutter',
    storageBucket: 'assistentflutter.firebasestorage.app',
    iosBundleId: 'com.example.siriGoogleAssistent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMjSRprdy2hnuc_Ce8cspRBPHgL7dsjek',
    appId: '1:569063379537:web:8f5d85990ccca5e05a1e70',
    messagingSenderId: '569063379537',
    projectId: 'assistentflutter',
    authDomain: 'assistentflutter.firebaseapp.com',
    storageBucket: 'assistentflutter.firebasestorage.app',
    measurementId: 'G-MBS66VLHES',
  );

}